# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=80)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('paired_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.user')),
            ],
            options={
                'db_table': 'devices_device',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('calories', models.PositiveIntegerField()),
                ('avg_heart_rate', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='devices.devicemodel')),
            ],
            options={
                'db_table': 'devices_workoutsession',
            },
        ),
    ]
