# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'subscriptions_plan',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.user')),
            ],
            options={
                'db_table': 'subscriptions_subscription',
            },
        ),
    ]
